### ISSUE TITLE
Пустой адресс сниппета если экспотрный сценарий был вызван ранее и вызывается в другом экспортном сценарии

### ISSUE THREAD

**Issue by NikitaLysenkoA** [Pr-Mex/vanessa-automation-single#2]
Укажите:
   1. Версия Vanessa Automation 1.2.038.7
   2. Версия платформы 8.3.20.1549
   3. Режим совместимости базы, где запускается Vanessa Automation: 8.3.14
   4. Windows 10

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: <Необходимый эффект>
   Как разработчик
   Я хочу вызывать части фич в одном сценарии

Контекст:
  Дано: Vanessa Automation single 1.2.038.7
  И 1С:Предприятие 8.3 (8.3.20.1549)
  и Бухгалтерия предприятия, редакция 3.0 (3.0.87.28) 

Сценарий: Пустой адрес сниппета
  Допустим: Есть экспортный сценарий который вызывается непосредственно и вызвается из другого экспортного сценария 
  Когда: открывается фича файл 
  Тогда: появляется ошибка "Не смог скопировать сценарий ..., т.к. произошло бы зацикливание."
  И дерево не формируется
  
  Когда: выполняется фича файл 
  Тогда: на сценарии который не прогрузился появляется ошибка "Пустой адрес снипета у шага"
  
```

> Прикладывайте файлы скриншотов
![изображение](https://user-images.githubusercontent.com/102023443/159242673-5f521d1b-d50a-4140-bf64-586849d0a074.png)

![изображение](https://user-images.githubusercontent.com/102023443/159241839-9cd6de1b-7fb8-4b16-87b7-29d02a9a2dfe.png)

**Comment by NikitaLysenkoA** [comment]
[ТестФичи.zip](https://github.com/Pr-Mex/vanessa-automation-single/files/8314656/default.zip)
Файлы сценария

**Comment by Pr-Mex** [comment]
@NikitaLysenkoA 
Добрый день.
1. issue нужно регистрировать тут, в основном репозитории https://github.com/Pr-Mex/vanessa-automation/issues
2. Проверьте ваш кейс на актуальной версии. Как раз по этому механизму недавно вносились изменения, но уже после 1.2.038.7
https://github.com/Pr-Mex/vanessa-automation/issues/1549

**Comment by NikitaLysenkoA** [comment]
Добрый день.
На 1.2.038.27 все ок. Спасибо.
