### ISSUE TITLE
Ошибка работы шага: И я создаю fixtures по макету "Макет"

### ISSUE THREAD

**Issue by KirillSidelnikov** [Pr-Mex/vanessa-automation-single#3]
1. Версия - 1.2.038.1
   2. Версия платформы - 8.3.16.1659
   3. Режим совместимости базы, где запускается Vanessa Automation - 8.3.14
   4. Операционная система - Windows 10

Шаг **И я создаю fixtures по макету "Макет"** падает с ошибкой:
{ВнешняяОбработка.VanessaAutomationsingle.Форма.УправляемаяФорма.Форма(13510)}: Ошибка при вызове метода контекста (ПолучитьФорму): Неизвестное имя формы. Имя: "ВнешняяОбработка.VanessaAutomationsingle.Форма.Плагин_СериализаторMXL"

Этот же шаг в версии 1.2.037.1 выполняется без ошибок.

```Gherkin
Функционал: загрузка данных из макета
   Как разработчик
   Я хочу загружать данные из макета

Контекст:
  Дано: VA-single ver. 1.2.038.1
  И 8.3.16.1659
  И режим совместимости 8.3.14

Сценарий: Загрузка данных из макета
  Допустим: необходимо загрузить данные из макета
  Когда: вызывается шаг **И я создаю fixtures по макету "Макет"**
  Тогда: загрузка данных проходит без ошибок

```

**Comment by Pr-Mex** [comment]
@KirillSidelnikov 
Проверьте на этом релизе, пожалуйста
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.038.27

**Comment by KirillSidelnikov** [comment]
@Pr-Mex
Спасибо, в предложенной версии всё работает правильно.
